export type SceneLayer = "back" | "mid" | "front";

export type SceneObject = {
  src: string;
  alt: string;
  layer: SceneLayer;
  top: string;
  left: string;
  width: number;
  rotate: number;
  z: number;
  floatAmplitude: number;
  floatDuration: number;
  floatDelay: number;
  mobile?: {
    top?: string;
    left?: string;
    width?: number;
    hidden?: boolean;
  };
};

export const PARALLAX_SPEED: Record<SceneLayer, number> = {
  back: 0.12,
  mid: 0.32,
  front: 0.55,
};

export const sceneObjects: SceneObject[] = [
  {
    src: "/assets/skvoznoe/ostrich.png",
    alt: "ostrich engraving",
    layer: "back",
    top: "5%",
    left: "6%",
    width: 420,
    rotate: -6,
    z: 1,
    floatAmplitude: 10,
    floatDuration: 15,
    floatDelay: 0.2,
    mobile: { top: "6%", left: "-16%", width: 220 },
  },
  {
    src: "/assets/skvoznoe/pelican.png",
    alt: "pelican engraving",
    layer: "back",
    top: "4%",
    left: "72%",
    width: 380,
    rotate: 4,
    z: 1,
    floatAmplitude: 8,
    floatDuration: 17,
    floatDelay: 1.3,
    mobile: { top: "8%", left: "62%", width: 180 },
  },
  {
    src: "/assets/skvoznoe/wine_press.png",
    alt: "wine press engraving",
    layer: "back",
    top: "41%",
    left: "78%",
    width: 300,
    rotate: -3,
    z: 1,
    floatAmplitude: 7,
    floatDuration: 16,
    floatDelay: 2.1,
    mobile: { hidden: true },
  },

  {
    src: "/assets/skvoznoe/duck_roast.png",
    alt: "duck roast engraving",
    layer: "mid",
    top: "18%",
    left: "39%",
    width: 340,
    rotate: 2,
    z: 2,
    floatAmplitude: 10,
    floatDuration: 14,
    floatDelay: 0.8,
    mobile: { top: "18%", left: "42%", width: 220 },
  },
  {
    src: "/assets/skvoznoe/sumo.png",
    alt: "sumo engraving",
    layer: "mid",
    top: "39%",
    left: "62%",
    width: 300,
    rotate: -2,
    z: 2,
    floatAmplitude: 8,
    floatDuration: 13,
    floatDelay: 1.1,
    mobile: { hidden: true },
  },
  {
    src: "/assets/skvoznoe/fish.png",
    alt: "fish engraving",
    layer: "mid",
    top: "71%",
    left: "13%",
    width: 260,
    rotate: 8,
    z: 2,
    floatAmplitude: 9,
    floatDuration: 12,
    floatDelay: 2.8,
    mobile: { top: "78%", left: "4%", width: 150 },
  },
  {
    src: "/assets/skvoznoe/book.png",
    alt: "book engraving",
    layer: "mid",
    top: "58%",
    left: "72%",
    width: 220,
    rotate: 12,
    z: 2,
    floatAmplitude: 7,
    floatDuration: 11,
    floatDelay: 0.5,
    mobile: { hidden: true },
  },
  {
    src: "/assets/skvoznoe/web_designer.png",
    alt: "web designer engraving",
    layer: "mid",
    top: "79%",
    left: "81%",
    width: 210,
    rotate: -4,
    z: 2,
    floatAmplitude: 6,
    floatDuration: 10,
    floatDelay: 1.7,
    mobile: { hidden: true },
  },

  {
    src: "/assets/skvoznoe/knuckles.png",
    alt: "knuckles engraving",
    layer: "front",
    top: "42%",
    left: "18%",
    width: 240,
    rotate: -12,
    z: 3,
    floatAmplitude: 10,
    floatDuration: 12,
    floatDelay: 0.4,
    mobile: { top: "48%", left: "0%", width: 160 },
  },
  {
    src: "/assets/skvoznoe/gold_teeth.png",
    alt: "gold teeth engraving",
    layer: "front",
    top: "64%",
    left: "47%",
    width: 260,
    rotate: 2,
    z: 3,
    floatAmplitude: 8,
    floatDuration: 10,
    floatDelay: 1.9,
    mobile: { top: "72%", left: "38%", width: 180 },
  },
  {
    src: "/assets/skvoznoe/axe_head.png",
    alt: "axe in head engraving",
    layer: "front",
    top: "12%",
    left: "48%",
    width: 240,
    rotate: -8,
    z: 3,
    floatAmplitude: 7,
    floatDuration: 12,
    floatDelay: 0.9,
    mobile: { top: "6%", left: "38%", width: 160 },
  },
  {
    src: "/assets/skvoznoe/matchbox.png",
    alt: "matchbox engraving",
    layer: "front",
    top: "61%",
    left: "2%",
    width: 210,
    rotate: 6,
    z: 3,
    floatAmplitude: 6,
    floatDuration: 11,
    floatDelay: 2.2,
    mobile: { top: "70%", left: "-2%", width: 130 },
  },
  {
    src: "/assets/skvoznoe/yogi.png",
    alt: "yogi engraving",
    layer: "front",
    top: "73%",
    left: "26%",
    width: 210,
    rotate: -3,
    z: 3,
    floatAmplitude: 8,
    floatDuration: 13,
    floatDelay: 1.2,
    mobile: { hidden: true },
  },
  {
    src: "/assets/skvoznoe/priest.png",
    alt: "priest engraving",
    layer: "front",
    top: "15%",
    left: "82%",
    width: 220,
    rotate: 4,
    z: 3,
    floatAmplitude: 7,
    floatDuration: 15,
    floatDelay: 2.7,
    mobile: { hidden: true },
  },
  {
    src: "/assets/skvoznoe/salo.png",
    alt: "salo engraving",
    layer: "front",
    top: "81%",
    left: "46%",
    width: 200,
    rotate: 1,
    z: 3,
    floatAmplitude: 5,
    floatDuration: 9,
    floatDelay: 0.6,
    mobile: { top: "84%", left: "62%", width: 120 },
  },
];
